import type { Metadata } from "next";
import "./globals.css";
import HeaderNav from "@/components/header-nav";
import { Nunito } from "next/font/google";


const nunito = Nunito({
    subsets: ['latin']
})


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={nunito.className}>
            <body>
                <header className="border-b">
                    <div className="container mx-auto flex h-24 items-center justify-center px-4">
                        <HeaderNav />
                    </div>
                </header>
                {children}
            </body>
        </html>
    );
}
