import type { Metadata } from "next";
import "./globals.css";
import HeaderNav from "@/components/header-nav";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <header className="border-b">
                    <div className="container mx-auto flex h-24 items-center justify-center px-4">
                        <HeaderNav />
                    </div>
                </header>
                {children}
            </body>
        </html>
    );
}
